"""baseline schema

Revision ID: da3e34b2b8fe
Revises: 
Create Date: 2026-07-12 17:20:51.850336
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3e34b2b8fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor'), 'audit_log', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_table('commit_validations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('blob_sha', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('extracted_variables', sa.JSON(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha', 'path', name='uq_validation')
    )
    op.create_index(op.f('ix_commit_validations_blob_sha'), 'commit_validations', ['blob_sha'], unique=False)
    op.create_index(op.f('ix_commit_validations_prompt_id'), 'commit_validations', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_commit_validations_sha'), 'commit_validations', ['sha'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('base_sha', sa.String(), nullable=True),
    sa.Column('git_ref', sa.String(), nullable=False),
    sa.Column('draft_sha', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_prompt_id'), 'drafts', ['prompt_id'], unique=False)
    op.create_table('environments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('track_tip', sa.Boolean(), nullable=False),
    sa.Column('rules_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('principals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_principals_subject'), 'principals', ['subject'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('review_policy', sa.Integer(), nullable=False),
    sa.Column('allow_self_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('auth_ref', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_pushed_sha', sa.String(), nullable=True),
    sa.Column('last_push_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('rules_version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_revisions_environment_id'), 'rule_revisions', ['environment_id'], unique=False)
    op.create_index(op.f('ix_rule_revisions_rule_id'), 'rule_revisions', ['rule_id'], unique=False)
    op.create_index(op.f('ix_rule_revisions_rules_version'), 'rule_revisions', ['rules_version'], unique=False)
    op.create_table('test_contexts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'name', name='uq_testctx')
    )
    op.create_index(op.f('ix_test_contexts_prompt_id'), 'test_contexts', ['prompt_id'], unique=False)
    op.create_table('variable_refinements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('default', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'version_number', 'name', name='uq_refinement')
    )
    op.create_index(op.f('ix_variable_refinements_prompt_id'), 'variable_refinements', ['prompt_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('principal_id', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_principal_id'), 'api_keys', ['principal_id'], unique=False)
    op.create_table('env_defaults',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment_id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id', 'prompt_id', name='uq_default')
    )
    op.create_index(op.f('ix_env_defaults_environment_id'), 'env_defaults', ['environment_id'], unique=False)
    op.create_index(op.f('ix_env_defaults_prompt_id'), 'env_defaults', ['prompt_id'], unique=False)
    op.create_table('kill_switches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment_id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('engaged', sa.Boolean(), nullable=False),
    sa.Column('by', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id', 'prompt_id', name='uq_kill')
    )
    op.create_index(op.f('ix_kill_switches_environment_id'), 'kill_switches', ['environment_id'], unique=False)
    op.create_index(op.f('ix_kill_switches_prompt_id'), 'kill_switches', ['prompt_id'], unique=False)
    op.create_table('pointer_moves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment_id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('from_sha', sa.String(), nullable=True),
    sa.Column('to_sha', sa.String(), nullable=False),
    sa.Column('moved_by', sa.String(), nullable=False),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pointer_moves_environment_id'), 'pointer_moves', ['environment_id'], unique=False)
    op.create_index(op.f('ix_pointer_moves_prompt_id'), 'pointer_moves', ['prompt_id'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('anchor', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_comments_draft_id'), 'review_comments', ['draft_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('reviewed_sha', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_draft_id'), 'reviews', ['draft_id'], unique=False)
    op.create_table('role_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('principal_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('environment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_bindings_principal_id'), 'role_bindings', ['principal_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('environment_id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('clauses', sa.JSON(), nullable=True),
    sa.Column('serve', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_environment_id'), 'rules', ['environment_id'], unique=False)
    op.create_index(op.f('ix_rules_prompt_id'), 'rules', ['prompt_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('clauses', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id', 'name', name='uq_segment')
    )
    op.create_index(op.f('ix_segments_environment_id'), 'segments', ['environment_id'], unique=False)
    op.create_table('versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'number', name='uq_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('versions')
    op.drop_index(op.f('ix_segments_environment_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_rules_prompt_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_environment_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_role_bindings_principal_id'), table_name='role_bindings')
    op.drop_table('role_bindings')
    op.drop_index(op.f('ix_reviews_draft_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_review_comments_draft_id'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_pointer_moves_prompt_id'), table_name='pointer_moves')
    op.drop_index(op.f('ix_pointer_moves_environment_id'), table_name='pointer_moves')
    op.drop_table('pointer_moves')
    op.drop_index(op.f('ix_kill_switches_prompt_id'), table_name='kill_switches')
    op.drop_index(op.f('ix_kill_switches_environment_id'), table_name='kill_switches')
    op.drop_table('kill_switches')
    op.drop_index(op.f('ix_env_defaults_prompt_id'), table_name='env_defaults')
    op.drop_index(op.f('ix_env_defaults_environment_id'), table_name='env_defaults')
    op.drop_table('env_defaults')
    op.drop_index(op.f('ix_api_keys_principal_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_variable_refinements_prompt_id'), table_name='variable_refinements')
    op.drop_table('variable_refinements')
    op.drop_index(op.f('ix_test_contexts_prompt_id'), table_name='test_contexts')
    op.drop_table('test_contexts')
    op.drop_index(op.f('ix_rule_revisions_rules_version'), table_name='rule_revisions')
    op.drop_index(op.f('ix_rule_revisions_rule_id'), table_name='rule_revisions')
    op.drop_index(op.f('ix_rule_revisions_environment_id'), table_name='rule_revisions')
    op.drop_table('rule_revisions')
    op.drop_table('remotes')
    op.drop_table('projects')
    op.drop_index(op.f('ix_principals_subject'), table_name='principals')
    op.drop_table('principals')
    op.drop_table('environments')
    op.drop_index(op.f('ix_drafts_prompt_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_commit_validations_sha'), table_name='commit_validations')
    op.drop_index(op.f('ix_commit_validations_prompt_id'), table_name='commit_validations')
    op.drop_index(op.f('ix_commit_validations_blob_sha'), table_name='commit_validations')
    op.drop_table('commit_validations')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
